name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  setup-python-on-26:
    runs-on: ubuntu-latest
    container: ubuntu:26.04
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - id: step1
        run: |
          which -a python
          cat /etc/lsb-release
          cat /etc/os-release
          find /__t/Python -type d -ls
          mount
  setup-python-on-24:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - id: step1
        run: |
          which -a python
          cat /etc/lsb-release
          cat /etc/os-release
          find /__t/Python -type d -ls
          mount
